### ISSUE TITLE
[BUG] Deno: Cannot access 'theme' before initialization

### ISSUE THREAD

**Issue by derheap** [speed-highlight/core#24]
**Information**
  
  * https://deno.land/x/speed_highlight_js@1.1.6
  * Speed-highlight.js from commit 472cc99a826651af80563fe2fdb2ad80f3c40d59  has the same error
  * Deno 1.18.2

**Description**

Running the Deno example fails with an error:

~~~~
error: Uncaught (in promise) ReferenceError: Cannot access 'theme' before initialization
        let res = '', theme = await theme;
                              ^
    at highlightText (file:///Users/tobias/code/speed-highlight--core/src/term.js:10:24)
    at printHighlight (file:///Users/tobias/code/speed-highlight--core/src/term.js:17:67)
    at file:///Users/tobias/code/speed-highlight--core/examples/deno.js:14:1
~~~~

**Example**

~~~~
$ git clone https://github.com/speed-highlight/core.git
$ cd core
$ deno run --allow-read examples/deno.js
~~~~

**Expected behavior**

Just print the highlighted code.

**Comment by matubu** [comment]
thanks for reporting

**Comment by derheap** [comment]
Thanks for fixing. 
It works now!
